-- Deterministic demo data, per docs/02-DATA-MODEL.md §16: one 'couple' space, two members,
-- the default category tree, four accounts, three tags, and three months of realistic
-- transactions across all five split modes, plus a handful of transfers and incomes.
--
-- Login as either demo user with password `password123`:
--   alex@demo.nido.local
--   sam@demo.nido.local
--
-- Fixed UUIDs (kept stable across `pnpm db:reset` runs so dev tooling, screenshots, and
-- Playwright fixtures can hardcode them):
--   auth users        : 00000000-0000-0000-0000-0000000000a1 (alex), 00000000-0000-0000-0000-0000000000a2 (sam)
--   sam's participant : 00000000-0000-0000-0000-0000000000a3
--   accounts          : 00000000-0000-0000-0000-0000000000b1 (joint checking)
--                        00000000-0000-0000-0000-0000000000b2 (joint savings)
--                        00000000-0000-0000-0000-0000000000b3 (alex cash)
--                        00000000-0000-0000-0000-0000000000b4 (sam card)
--   tags              : 00000000-0000-0000-0000-0000000000c1 (groceries-club)
--                        00000000-0000-0000-0000-0000000000c2 (reimbursable)
--                        00000000-0000-0000-0000-0000000000c3 (holidays-2026)
-- The space id, alex's participant id, and every transaction id are generated by the real
-- RPCs (`nido.create_space` / `nido.create_transaction`), exactly as the app would create
-- them, so they are not fixed — only the identities you need to log in and the rows we
-- insert directly are.
--
-- PERF NOTE: this seeds ~150 transactions (enough for a useful ledger and to exercise every
-- split mode many times over) rather than the 10,000 mentioned as a Phase 02 acceptance
-- criterion for scroll/virtualization testing. Generating 10k rows through the real
-- `create_transaction` RPC (one round trip + splits insert + audit row each) is too slow to
-- run on every `db:reset`. A dedicated perf seed (e.g. `supabase/seeds/perf_10k.sql`,
-- inserting `nido.transactions` / `nido.transaction_splits` directly with `generate_series`
-- and skipping the RPC/audit path) should be added when the ledger virtualization work in
-- Phase 02 §5 needs a large dataset to test against — see docs/BACKLOG.md.

begin;

-- ---------------------------------------------------------------------------------------
-- 1. Demo auth users (mirrors tests.create_user in supabase/tests/050_tenancy_rls.sql).
--    nido.profiles rows are created automatically by the on_auth_user_created trigger.
-- ---------------------------------------------------------------------------------------

insert into auth.users (
  id, instance_id, aud, role, email, encrypted_password,
  email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
  created_at, updated_at
) values
  (
    '00000000-0000-0000-0000-0000000000a1',
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated',
    'alex@demo.nido.local',
    extensions.crypt('password123', extensions.gen_salt('bf')),
    now(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    jsonb_build_object('display_name', 'Alex'),
    now(),
    now()
  ),
  (
    '00000000-0000-0000-0000-0000000000a2',
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated',
    'sam@demo.nido.local',
    extensions.crypt('password123', extensions.gen_salt('bf')),
    now(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    jsonb_build_object('display_name', 'Sam'),
    now(),
    now()
  );

-- ---------------------------------------------------------------------------------------
-- 2. Everything else, as one deterministic script. `seed.sql` runs as the migration role,
--    which bypasses RLS entirely, so the only thing that matters for the RPCs below is
--    `auth.uid()` (read from the `request.jwt.claim.sub` / `request.jwt.claims` session
--    settings) — there is no need to `set role`. We flip that setting to whichever demo
--    user is "acting" right before every RPC call, exactly like a real request from their
--    session would.
-- ---------------------------------------------------------------------------------------

do $$
declare
  v_alex_id constant uuid := '00000000-0000-0000-0000-0000000000a1';
  v_sam_id  constant uuid := '00000000-0000-0000-0000-0000000000a2';
  v_sam_participant constant uuid := '00000000-0000-0000-0000-0000000000a3';

  v_account_checking constant uuid := '00000000-0000-0000-0000-0000000000b1';
  v_account_savings  constant uuid := '00000000-0000-0000-0000-0000000000b2';
  v_account_alex_cash constant uuid := '00000000-0000-0000-0000-0000000000b3';
  v_account_sam_card  constant uuid := '00000000-0000-0000-0000-0000000000b4';

  v_tag_groceries_club constant uuid := '00000000-0000-0000-0000-0000000000c1';
  v_tag_reimbursable   constant uuid := '00000000-0000-0000-0000-0000000000c2';
  v_tag_holidays       constant uuid := '00000000-0000-0000-0000-0000000000c3';

  v_space_id uuid;
  v_alex_participant uuid;

  -- Expense scenarios: category name (must match supabase/migrations/20260810120900_seed_categories.sql),
  -- description, merchant, and an amount range in minor units (cents). Cycled through by index.
  v_exp_name text[] := array[
    'Groceries', 'Eating out', 'Transport', 'Leisure', 'Shopping', 'Health',
    'Subscriptions', 'Housing', 'Pets', 'Travel', 'Education', 'Gifts',
    'Fees', 'Other', 'Groceries', 'Eating out', 'Transport', 'Shopping',
    'Leisure', 'Health'
  ];
  v_exp_desc text[] := array[
    'Weekly grocery shop', 'Dinner out', 'Metro pass top-up', 'Cinema tickets',
    'New clothes', 'Pharmacy', 'Streaming subscription', 'Monthly rent',
    'Pet food', 'Weekend train trip', 'Online course', 'Birthday gift',
    'Bank fee', 'Miscellaneous purchase', 'Fruit market', 'Coffee run',
    'Ride share', 'Home goods', 'Gym membership', 'Dental check-up'
  ];
  v_exp_merchant text[] := array[
    'Mercadona', 'Casa Paco', 'Metro Madrid', 'Cines Ideal', 'Zara',
    'Farmacia Central', 'Netflix', 'Inmobiliaria Sol', 'Kiwoko', 'Renfe',
    'Udemy', 'El Corte Ingles', 'Banco Santander', 'Varios',
    'Mercado San Miguel', 'Cafe Central', 'Cabify', 'IKEA', 'Basic Fit',
    'Clinica Dental'
  ];
  v_exp_min bigint[] := array[1800, 1200, 400, 900, 2000, 500, 1299, 65000, 1500, 3000, 1000, 1500, 100, 300, 800, 250, 500, 1500, 2999, 2000]::bigint[];
  v_exp_max bigint[] := array[6200, 5500, 2000, 2400, 12000, 3500, 1299, 65000, 4500, 15000, 6000, 8000, 500, 2500, 3000, 900, 2500, 9000, 2999, 9000]::bigint[];
  v_exp_cat_id uuid[] := array_fill(null::uuid, array[20]);

  -- Income scenarios, same shape.
  v_inc_name text[] := array['Salary', 'Freelance', 'Refunds', 'Gifts', 'Investments', 'Other'];
  v_inc_desc text[] := array[
    'Monthly salary', 'Freelance project payout', 'Online store refund',
    'Gift from family', 'Dividend payout', 'Card cashback'
  ];
  v_inc_merchant text[] := array[
    'Empresa SL', 'Cliente Freelance', 'Amazon', 'Familia', 'Broker XYZ', 'Tarjeta rewards'
  ];
  v_inc_min bigint[] := array[150000, 20000, 500, 2000, 1000, 200]::bigint[];
  v_inc_max bigint[] := array[160000, 80000, 5000, 10000, 15000, 2000]::bigint[];
  v_inc_cat_id uuid[] := array_fill(null::uuid, array[6]);

  v_share_w1 int[] := array[2, 3, 1, 3, 1];
  v_share_w2 int[] := array[1, 1, 2, 2, 3];
  v_pct1 int[] := array[60, 70, 50, 65, 80];
  v_pct2 int[] := array[40, 30, 50, 35, 20];

  v_n int;
  v_idx int;
  v_mode_idx int;
  v_kind text;
  v_split_mode text;
  v_booked date;
  v_amount bigint;
  v_range bigint;
  v_category_id uuid;
  v_description text;
  v_merchant text;
  v_account_id uuid;
  v_payer_participant uuid;
  v_actor uuid;
  v_participants jsonb;
  v_params jsonb;
  v_tag_ids uuid[];
  v_w1 int;
  v_w2 int;
  v_owed_alex bigint;
  v_owed_sam bigint;
  v_ratio numeric;
  v_transfer_seq int;
  v_from_account uuid;
  v_to_account uuid;
  v_n_transactions int := 0;
  v_n_transfers int := 0;
  v_n_incomes int := 0;
  v_n_expenses int := 0;
begin
  -- 2a. Alex creates the couple space (owner participant + default categories, atomically).
  perform set_config('request.jwt.claim.sub', v_alex_id::text, true);
  perform set_config('request.jwt.claim.role', 'authenticated', true);
  perform set_config(
    'request.jwt.claims',
    json_build_object('sub', v_alex_id::text, 'role', 'authenticated', 'email', 'alex@demo.nido.local')::text,
    true
  );

  v_space_id := nido.create_space(
    'Casa de Alex y Sam', 'couple', 'EUR', 'Europe/Madrid', '[]'::jsonb
  );

  select p.id into v_alex_participant
  from nido.participants p
  where p.space_id = v_space_id and p.user_id = v_alex_id;

  -- 2b. Add Sam as a real, active member (direct inserts — same shape create_space used for
  -- Alex, done manually since create_space only seeds the caller plus ghost participants).
  insert into nido.participants (id, space_id, user_id, display_name, color, position)
  values (v_sam_participant, v_space_id, v_sam_id, 'Sam', '#6B8EAD', 1);

  insert into nido.space_members (space_id, user_id, participant_id, role, status)
  values (v_space_id, v_sam_id, v_sam_participant, 'member', 'active');

  -- 2c. Four accounts.
  insert into nido.accounts (
    id, space_id, name, kind, currency, owner_participant_id, opening_balance_minor,
    color, icon, position
  ) values
    (v_account_checking, v_space_id, 'Cuenta Conjunta', 'bank', 'EUR', null, 250000, '#5B8A7A', 'wallet', 0),
    (v_account_savings, v_space_id, 'Ahorro Conjunto', 'savings', 'EUR', null, 800000, '#7BA3A8', 'piggy-bank', 1),
    (v_account_alex_cash, v_space_id, 'Efectivo Alex', 'cash', 'EUR', v_alex_participant, 5000, '#C49A6C', 'banknote', 2),
    (v_account_sam_card, v_space_id, 'Tarjeta Sam', 'card', 'EUR', v_sam_participant, -15000, '#9B8EC4', 'credit-card', 3);

  -- 2d. Three tags.
  insert into nido.tags (id, space_id, name, color) values
    (v_tag_groceries_club, v_space_id, 'groceries-club', '#8FBC8F'),
    (v_tag_reimbursable, v_space_id, 'reimbursable', '#D4849A'),
    (v_tag_holidays, v_space_id, 'holidays-2026', '#6A9BC3');

  -- 2e. Resolve category ids once, by name + kind (both expense and income trees contain a
  -- 'Gifts' and an 'Other' category, so the kind filter disambiguates them).
  for v_idx in 1..array_length(v_exp_name, 1) loop
    select c.id into v_exp_cat_id[v_idx]
    from nido.categories c
    where c.space_id = v_space_id and c.kind = 'expense' and c.name = v_exp_name[v_idx];
  end loop;

  for v_idx in 1..array_length(v_inc_name, 1) loop
    select c.id into v_inc_cat_id[v_idx]
    from nido.categories c
    where c.space_id = v_space_id and c.kind = 'income' and c.name = v_inc_name[v_idx];
  end loop;

  -- 2f. ~150 transactions spread across three months (2026-05-01 .. 2026-07-31), covering
  -- all five split modes, a handful of transfers, and a handful of incomes.
  for v_n in 1..150 loop
    v_booked := date '2026-05-01' + (((v_n - 1) * 37) % 92);
    v_payer_participant := case when v_n % 2 = 0 then v_sam_participant else v_alex_participant end;
    v_actor := case when v_n % 2 = 0 then v_sam_id else v_alex_id end;

    if v_n % 15 = 0 then
      v_kind := 'transfer';
    elsif v_n % 10 = 0 then
      v_kind := 'income';
    else
      v_kind := 'expense';
    end if;

    perform set_config('request.jwt.claim.sub', v_actor::text, true);
    perform set_config('request.jwt.claim.role', 'authenticated', true);
    perform set_config(
      'request.jwt.claims',
      json_build_object(
        'sub', v_actor::text, 'role', 'authenticated',
        'email', case when v_actor = v_alex_id then 'alex@demo.nido.local' else 'sam@demo.nido.local' end
      )::text,
      true
    );

    if v_kind = 'transfer' then
      v_transfer_seq := v_n / 15;
      case (v_transfer_seq - 1) % 3
        when 0 then
          v_from_account := v_account_checking;
          v_to_account := v_account_savings;
          v_amount := 20000 + ((v_n * 977) % 60001);
        when 1 then
          v_from_account := v_account_checking;
          v_to_account := v_account_alex_cash;
          v_amount := 3000 + ((v_n * 977) % 7001);
        else
          v_from_account := v_account_savings;
          v_to_account := v_account_checking;
          v_amount := 10000 + ((v_n * 977) % 30001);
      end case;

      v_params := jsonb_build_object(
        'space_id', v_space_id,
        'kind', 'transfer',
        'booked_on', v_booked,
        'amount_minor', v_amount,
        'currency', 'EUR',
        'description', 'Transfer between accounts',
        'account_id', v_from_account,
        'to_account_id', v_to_account
      );

      perform nido.create_transaction(v_params);
      v_n_transfers := v_n_transfers + 1;

    elsif v_kind = 'income' then
      v_idx := ((v_n - 1) % array_length(v_inc_name, 1)) + 1;
      v_range := greatest(v_inc_max[v_idx] - v_inc_min[v_idx] + 1, 1);
      v_amount := v_inc_min[v_idx] + ((v_n * 977 + v_idx * 131) % v_range);
      v_category_id := v_inc_cat_id[v_idx];
      v_description := v_inc_desc[v_idx];
      v_merchant := v_inc_merchant[v_idx];
      v_split_mode := case when v_n % 20 = 0 then 'equal' else 'personal' end;

      v_participants := case v_split_mode
        when 'equal' then jsonb_build_array(
          jsonb_build_object('participant_id', v_alex_participant),
          jsonb_build_object('participant_id', v_sam_participant)
        )
        else jsonb_build_array(jsonb_build_object('participant_id', v_payer_participant))
      end;

      v_params := jsonb_build_object(
        'space_id', v_space_id,
        'kind', 'income',
        'booked_on', v_booked,
        'amount_minor', v_amount,
        'currency', 'EUR',
        'split_mode', v_split_mode,
        'description', v_description,
        'merchant', v_merchant,
        'category_id', v_category_id,
        'account_id', v_account_checking,
        'payer_participant_id', v_payer_participant,
        'participants', v_participants
      );

      perform nido.create_transaction(v_params);
      v_n_incomes := v_n_incomes + 1;

    else
      v_idx := ((v_n - 1) % array_length(v_exp_name, 1)) + 1;
      v_range := greatest(v_exp_max[v_idx] - v_exp_min[v_idx] + 1, 1);
      v_amount := v_exp_min[v_idx] + ((v_n * 977 + v_idx * 131) % v_range);
      v_category_id := v_exp_cat_id[v_idx];
      v_description := v_exp_desc[v_idx];
      v_merchant := v_exp_merchant[v_idx];

      v_split_mode := case v_n % 5
        when 0 then 'personal'
        when 1 then 'equal'
        when 2 then 'shares'
        when 3 then 'percent'
        else 'exact'
      end;

      v_account_id := case v_n % 3
        when 0 then v_account_checking
        when 1 then v_account_alex_cash
        else v_account_sam_card
      end;

      if v_split_mode = 'personal' then
        v_participants := jsonb_build_array(jsonb_build_object('participant_id', v_payer_participant));
      elsif v_split_mode = 'equal' then
        v_participants := jsonb_build_array(
          jsonb_build_object('participant_id', v_alex_participant),
          jsonb_build_object('participant_id', v_sam_participant)
        );
      elsif v_split_mode = 'shares' then
        v_mode_idx := ((v_n - 1) % 5) + 1;
        v_w1 := v_share_w1[v_mode_idx];
        v_w2 := v_share_w2[v_mode_idx];
        v_participants := jsonb_build_array(
          jsonb_build_object('participant_id', v_alex_participant, 'weight', v_w1),
          jsonb_build_object('participant_id', v_sam_participant, 'weight', v_w2)
        );
      elsif v_split_mode = 'percent' then
        v_mode_idx := ((v_n - 1) % 5) + 1;
        v_participants := jsonb_build_array(
          jsonb_build_object('participant_id', v_alex_participant, 'weight', v_pct1[v_mode_idx]),
          jsonb_build_object('participant_id', v_sam_participant, 'weight', v_pct2[v_mode_idx])
        );
      else -- exact
        v_ratio := case (v_n - 1) % 3 when 0 then 0.5 when 1 then 0.6 else 0.7 end;
        v_owed_alex := round(v_amount * v_ratio)::bigint;
        v_owed_sam := v_amount - v_owed_alex;
        v_participants := jsonb_build_array(
          jsonb_build_object('participant_id', v_alex_participant, 'owed_minor', v_owed_alex),
          jsonb_build_object('participant_id', v_sam_participant, 'owed_minor', v_owed_sam)
        );
      end if;

      v_tag_ids := null;
      if v_exp_name[v_idx] = 'Travel' then
        v_tag_ids := array[v_tag_holidays];
      elsif v_exp_name[v_idx] = 'Groceries' and v_n % 4 = 0 then
        v_tag_ids := array[v_tag_groceries_club];
      elsif v_exp_name[v_idx] = 'Health' and v_n % 3 = 0 then
        v_tag_ids := array[v_tag_reimbursable];
      end if;

      v_params := jsonb_build_object(
        'space_id', v_space_id,
        'kind', 'expense',
        'booked_on', v_booked,
        'amount_minor', v_amount,
        'currency', 'EUR',
        'split_mode', v_split_mode,
        'description', v_description,
        'merchant', v_merchant,
        'category_id', v_category_id,
        'account_id', v_account_id,
        'payer_participant_id', v_payer_participant,
        'participants', v_participants
      );
      if v_tag_ids is not null then
        v_params := v_params || jsonb_build_object('tag_ids', to_jsonb(v_tag_ids));
      end if;

      perform nido.create_transaction(v_params);
      v_n_expenses := v_n_expenses + 1;
    end if;

    v_n_transactions := v_n_transactions + 1;
  end loop;

  raise notice
    'Seeded space % ("Casa de Alex y Sam") with % transactions (% expenses, % incomes, % transfers).',
    v_space_id, v_n_transactions, v_n_expenses, v_n_incomes, v_n_transfers;
end $$;

commit;
