-- Phase 09 — period snapshots, monthly close RPC, and period-close notifications.

alter type nido.notification_kind add value if not exists 'period_close';

create table nido.period_snapshots (
  id           uuid primary key default gen_random_uuid(),
  space_id     uuid not null references nido.spaces (id) on delete cascade,
  period_from  date not null,
  period_to    date not null,
  payload      jsonb not null,
  created_at   timestamptz not null default now(),
  constraint period_snapshots_range check (period_from <= period_to),
  unique (space_id, period_from, period_to)
);

create index period_snapshots_space_created_idx
  on nido.period_snapshots (space_id, created_at desc);

comment on table nido.period_snapshots is
  'Stored monthly (or custom) close documents generated by period-close.';

alter table nido.period_snapshots enable row level security;

create policy "period_snapshots_select_members"
  on nido.period_snapshots for select
  using (nido.is_member(space_id));

create policy "period_snapshots_insert_service"
  on nido.period_snapshots for insert
  with check (auth.role() = 'service_role');

grant select on nido.period_snapshots to authenticated, service_role;
grant insert, delete on nido.period_snapshots to service_role;

create or replace function nido.period_snapshot(
  p_space_id uuid,
  p_from date,
  p_to date
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_space record;
  v_summary jsonb;
  v_prev_from date;
  v_prev_to date;
  v_days integer;
  v_budgets jsonb;
  v_goals jsonb;
  v_subscriptions jsonb;
  v_settlements jsonb;
  v_top_changes jsonb;
  v_result jsonb;
begin
  if auth.role() is distinct from 'service_role' and not nido.is_member(p_space_id) then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  if p_from is null or p_to is null or p_from > p_to then
    raise exception 'invalid date range' using errcode = '22023';
  end if;

  select s.id, s.name, s.base_currency, s.timezone, s.month_starts_on
    into v_space
  from nido.spaces s
  where s.id = p_space_id;

  if not found then
    raise exception 'space not found' using errcode = 'P0002';
  end if;

  v_summary := nido.space_summary(p_space_id, p_from, p_to, null);

  v_days := (p_to - p_from) + 1;
  v_prev_to := p_from - 1;
  v_prev_from := v_prev_to - (v_days - 1);

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', b.id,
        'name', b.name,
        'scope', b.scope,
        'limit_minor', bp.limit_minor,
        'spent_minor', bp.spent_minor,
        'remaining_minor', bp.limit_minor - bp.spent_minor,
        'percent_used',
          case when bp.limit_minor = 0 then 0
          else round((bp.spent_minor::numeric / bp.limit_minor::numeric), 6)
          end
      )
      order by b.name
    ),
    '[]'::jsonb
  )
    into v_budgets
  from nido.budgets b
  join nido.budget_periods bp on bp.budget_id = b.id
  where b.space_id = p_space_id
    and b.is_active
    and bp.starts_on <= p_to
    and bp.ends_on >= p_from;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', g.id,
        'name', g.name,
        'target_minor', g.target_minor,
        'saved_minor', g.saved_minor,
        'currency', g.currency,
        'status', g.status,
        'progress',
          case when g.target_minor = 0 then 0
          else round((g.saved_minor::numeric / g.target_minor::numeric), 6)
          end
      )
      order by g.name
    ),
    '[]'::jsonb
  )
    into v_goals
  from nido.goals g
  where g.space_id = p_space_id
    and g.status in ('active', 'reached');

  select coalesce(
    jsonb_build_object(
      'count', count(*)::integer,
      'monthly_cost_minor', coalesce(sum(r.amount_minor), 0)::bigint
    ),
    jsonb_build_object('count', 0, 'monthly_cost_minor', 0)
  )
    into v_subscriptions
  from nido.recurring_rules r
  where r.space_id = p_space_id
    and r.kind = 'subscription'
    and r.is_active
    and r.cancelled_at is null;

  select coalesce(
    jsonb_build_object(
      'count', count(*)::integer,
      'total_minor', coalesce(sum(s.base_amount_minor), 0)::bigint
    ),
    jsonb_build_object('count', 0, 'total_minor', 0)
  )
    into v_settlements
  from nido.settlements s
  where s.space_id = p_space_id
    and s.confirmed_at is not null
    and s.settled_on between p_from and p_to;

  with
  current_cat as (
    select
      c.id,
      coalesce(c.name, '—') as name,
      c.color,
      sum(t.base_amount_minor)::bigint as total_minor
    from nido.transactions t
    left join nido.categories c on c.id = t.category_id
    where t.space_id = p_space_id
      and t.deleted_at is null
      and t.kind = 'expense'
      and t.booked_on between p_from and p_to
    group by c.id, c.name, c.color
  ),
  previous_cat as (
    select
      t.category_id as id,
      sum(t.base_amount_minor)::bigint as total_minor
    from nido.transactions t
    where t.space_id = p_space_id
      and t.deleted_at is null
      and t.kind = 'expense'
      and t.booked_on between v_prev_from and v_prev_to
    group by t.category_id
  ),
  deltas as (
    select
      cc.id,
      cc.name,
      cc.color,
      cc.total_minor as current_minor,
      coalesce(pc.total_minor, 0)::bigint as previous_minor,
      cc.total_minor - coalesce(pc.total_minor, 0)::bigint as change_minor
    from current_cat cc
    left join previous_cat pc on pc.id is not distinct from cc.id
  )
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', d.id,
        'name', d.name,
        'color', d.color,
        'current_minor', d.current_minor,
        'previous_minor', d.previous_minor,
        'change_minor', d.change_minor
      )
      order by abs(d.change_minor) desc, d.name
    ),
    '[]'::jsonb
  )
    into v_top_changes
  from (
    select * from deltas
    order by abs(change_minor) desc, name
    limit 3
  ) d;

  v_result := v_summary || jsonb_build_object(
    'space_id', p_space_id,
    'space_name', v_space.name,
    'base_currency', v_space.base_currency,
    'timezone', v_space.timezone,
    'budgets', v_budgets,
    'goals', v_goals,
    'subscriptions', v_subscriptions,
    'settlements', v_settlements,
    'top_changes', v_top_changes
  );

  return v_result;
end;
$$;

comment on function nido.period_snapshot(uuid, date, date) is
  'Complete monthly close document: dashboard summary plus budgets, goals, subscriptions, settlements, top changes.';

revoke all on function nido.period_snapshot(uuid, date, date) from public;
grant execute on function nido.period_snapshot(uuid, date, date) to authenticated, service_role;

-- Persist a snapshot and notify all active members.
create or replace function nido.store_period_snapshot(
  p_space_id uuid,
  p_from date,
  p_to date
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_payload jsonb;
  v_id uuid;
  v_member record;
begin
  if auth.role() is distinct from 'service_role' then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  v_payload := nido.period_snapshot(p_space_id, p_from, p_to);

  insert into nido.period_snapshots (space_id, period_from, period_to, payload)
  values (p_space_id, p_from, p_to, v_payload)
  on conflict (space_id, period_from, period_to)
  do update set payload = excluded.payload, created_at = now()
  returning id into v_id;

  for v_member in
    select sm.user_id
    from nido.space_members sm
    where sm.space_id = p_space_id
      and sm.status = 'active'
  loop
    insert into nido.notifications (
      space_id, user_id, kind, title, body, payload
    ) values (
      p_space_id,
      v_member.user_id,
      'period_close',
      'Monthly close ready',
      format('Your %s to %s close is ready.', p_from, p_to),
      jsonb_build_object(
        'snapshot_id', v_id,
        'period_from', p_from,
        'period_to', p_to
      )
    );
  end loop;

  return v_id;
end;
$$;

revoke all on function nido.store_period_snapshot(uuid, date, date) from public;
grant execute on function nido.store_period_snapshot(uuid, date, date) to service_role;

-- Spaces whose household month starts today (in their timezone) get the previous period closed.
create or replace function nido.run_period_close_all()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_space record;
  v_today date;
  v_month_start date;
  v_prev_from date;
  v_prev_to date;
  v_closed integer := 0;
  v_ids uuid[] := '{}'::uuid[];
  v_id uuid;
begin
  for v_space in
    select s.id, s.timezone, s.month_starts_on
    from nido.spaces s
    where s.archived_at is null
  loop
    v_today := (now() at time zone v_space.timezone)::date;
    v_month_start := nido.household_month_start(v_today, v_space.month_starts_on);

    if v_today <> v_month_start then
      continue;
    end if;

    v_prev_to := v_month_start - 1;
    v_prev_from := nido.household_month_start(v_prev_to, v_space.month_starts_on);

    v_id := nido.store_period_snapshot(v_space.id, v_prev_from, v_prev_to);
    v_closed := v_closed + 1;
    v_ids := array_append(v_ids, v_id);
  end loop;

  return jsonb_build_object('closed', v_closed, 'snapshot_ids', to_jsonb(v_ids));
end;
$$;

revoke all on function nido.run_period_close_all() from public;
grant execute on function nido.run_period_close_all() to service_role;

-- Upsert FX rates (called by fx-refresh Edge Function).
create or replace function nido.upsert_exchange_rates(p_rates jsonb)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row jsonb;
  v_count integer := 0;
begin
  if auth.role() is distinct from 'service_role' then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  for v_row in select * from jsonb_array_elements(p_rates) loop
    insert into nido.exchange_rates (base, quote, rate, as_of, source)
    values (
      (v_row ->> 'base')::nido.currency_code,
      (v_row ->> 'quote')::nido.currency_code,
      (v_row ->> 'rate')::numeric,
      (v_row ->> 'as_of')::date,
      coalesce(v_row ->> 'source', 'frankfurter')
    )
    on conflict (base, quote, as_of)
    do update set rate = excluded.rate, source = excluded.source;
    v_count := v_count + 1;
  end loop;

  return v_count;
end;
$$;

revoke all on function nido.upsert_exchange_rates(jsonb) from public;
grant execute on function nido.upsert_exchange_rates(jsonb) to service_role;
